services:
  db:
    image: postgres:16
    container_name: forgio_db
    restart: always
    environment:
      POSTGRES_USER: majestycomaa
      POSTGRES_PASSWORD: VFREJpassword
      POSTGRES_DB: forgio_db
    ports:
      - "5433:5432"
    volumes:
      - ./Forgio/src/main/resources/db/migration:/docker-entrypoint-initdb.d