services:
  db:
    image: postgres:16
    container_name: forgio-db
    environment:
      POSTGRES_DB: forgio_db
      POSTGRES_USER: forgio
      POSTGRES_PASSWORD: forgio_secret
    ports:
      - "5432:5432"
    volumes:
      - forgio_data:/var/lib/postgresql/data

volumes:
  forgio_data: